import { useState, useCallback } from "react";

const TEAL = "#0B6E6E";
const TEAL_LIGHT = "#E6F4F4";
const NAVY = "#0D2B45";
const CREAM = "#FAF8F4";
const GOLD = "#C49A3C";
const RED = "#C0392B";

function pdfToBase64(file) {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(reader.result.split(",")[1]);
    reader.onerror = reject;
    reader.readAsDataURL(file);
  });
}

function generateDownload(formTitle, fields, fileName) {
  const lines = [
    `COMPLETED FORM: ${formTitle}`,
    `Generated: ${new Date().toLocaleString()}`,
    "=".repeat(50),
    "",
  ];
  fields.forEach(({ label, value }) => {
    lines.push(`${label}:`);
    lines.push(`  ${value}`);
    lines.push("");
  });
  lines.push("=".repeat(50));
  lines.push("Generated by Clinical Form Completion Tool");
  const blob = new Blob([lines.join("\n")], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `completed_${fileName.replace(".pdf", "")}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

export default function App() {
  const [pdfFile, setPdfFile] = useState(null);
  const [freeText, setFreeText] = useState("");
  const [dragging, setDragging] = useState(false);
  const [loading, setLoading] = useState(false);
  const [progress, setProgress] = useState("");
  const [result, setResult] = useState(null);
  const [error, setError] = useState("");
  const [apiKey, setApiKey] = useState("");

  const handleDrop = useCallback((e) => {
    e.preventDefault();
    setDragging(false);
    const file = e.dataTransfer.files[0];
    if (file && file.type === "application/pdf") setPdfFile(file);
  }, []);

  const canRun = pdfFile && freeText.trim().length > 10 && !loading && apiKey.trim().length > 10;

  const run = async () => {
    if (!canRun) return;
    setLoading(true);
    setError("");
    setResult(null);

    try {
      setProgress("Reading PDF form...");
      const base64 = await pdfToBase64(pdfFile);
      setProgress("Analysing form fields and matching your notes...");

      const response = await fetch("https://api.anthropic.com/v1/messages", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "x-api-key": apiKey,
          "anthropic-version": "2023-06-01",
          "anthropic-dangerous-direct-browser-access": "true",
        },
        body: JSON.stringify({
          model: "claude-sonnet-4-5",
          max_tokens: 1500,
          system: `You are a clinical documentation assistant helping a Nurse Practitioner complete medical forms accurately. 
You will receive a PDF form and clinical notes. Extract all visible form fields from the PDF, then use the clinical notes to fill each field with the most appropriate value.
Respond ONLY with a JSON object in this exact format (no markdown, no explanation):
{
  "form_title": "name of the form",
  "fields": [
    {"label": "field name", "value": "completed value"}
  ],
  "unfilled_fields": ["fields that couldn't be completed from the notes"],
  "summary": "one sentence summary of what was completed"
}`,
          messages: [
            {
              role: "user",
              content: [
                {
                  type: "document",
                  source: { type: "base64", media_type: "application/pdf", data: base64 },
                },
                { type: "text", text: `Clinical notes:\n${freeText}` },
              ],
            },
          ],
        }),
      });

      const data = await response.json();
      if (data.error) throw new Error(data.error.message);

      const text = data.content.filter(b => b.type === "text").map(b => b.text).join("");
      const clean = text.replace(/```json|```/g, "").trim();
      const parsed = JSON.parse(clean);
      setProgress("");
      setResult({ ...parsed, fileName: pdfFile.name });
    } catch (err) {
      setProgress("");
      setError(err.message.includes("JSON") ? "Unexpected response format. Please try again." : `Error: ${err.message}`);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div style={{ minHeight: "100vh", background: CREAM, fontFamily: "Georgia, serif" }}>
      <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>

      <div style={{ background: NAVY, padding: "28px 40px", display: "flex", alignItems: "center", gap: 16, borderBottom: `4px solid ${GOLD}` }}>
        <div style={{ width: 44, height: 44, background: GOLD, borderRadius: "50%", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 22 }}>📋</div>
        <div>
          <h1 style={{ color: "#fff", fontSize: 22, fontWeight: "bold", margin: 0 }}>Clinical Form Completion Tool</h1>
          <div style={{ color: "#9BB5C8", fontSize: 13, fontFamily: "sans-serif" }}>Upload a form · Add your clinical notes · Download completed</div>
        </div>
      </div>

      <div style={{ maxWidth: 900, margin: "0 auto", padding: "40px 24px" }}>

        <div style={{ background: "#fff", borderRadius: 12, border: "1px solid #DDE4EB", padding: 24, marginBottom: 24, boxShadow: "0 2px 12px rgba(13,43,69,0.06)" }}>
          <div style={{ color: NAVY, fontSize: 13, fontWeight: "bold", fontFamily: "sans-serif", textTransform: "uppercase", letterSpacing: 1, marginBottom: 10 }}>🔑 Anthropic API Key</div>
          <input
            type="password"
            placeholder="sk-ant-..."
            value={apiKey}
            onChange={e => setApiKey(e.target.value)}
            style={{ width: "100%", border: "1.5px solid #DDE4EB", borderRadius: 8, padding: "12px 16px", fontFamily: "sans-serif", fontSize: 14, color: NAVY, outline: "none", boxSizing: "border-box" }}
          />
          <div style={{ fontSize: 12, color: "#8A9BAA", fontFamily: "sans-serif", marginTop: 8 }}>
            Get your key at console.anthropic.com — your key stays in your browser only, never stored.
          </div>
        </div>

        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 24, marginBottom: 24 }}>

          <div style={{ background: "#fff", borderRadius: 12, border: "1px solid #DDE4EB", padding: 28, boxShadow: "0 2px 12px rgba(13,43,69,0.06)" }}>
            <div style={{ color: NAVY, fontSize: 13, fontWeight: "bold", fontFamily: "sans-serif", textTransform: "uppercase", letterSpacing: 1, marginBottom: 16 }}>📄 PDF Form</div>
            <div
              onDragOver={e => { e.preventDefault(); setDragging(true); }}
              onDragLeave={() => setDragging(false)}
              onDrop={handleDrop}
              style={{ border: `2px dashed ${dragging ? TEAL : "#B8C8D8"}`, borderRadius: 10, padding: "30px 20px", textAlign: "center", background: dragging ? TEAL_LIGHT : "#F8FBFD", transition: "all 0.2s" }}
            >
              <div style={{ fontSize: 36, marginBottom: 10 }}>📂</div>
              <div style={{ color: "#5A7A8A", fontFamily: "sans-serif", fontSize: 13, marginBottom: 14 }}>
                <strong>Drop your PDF here</strong><br />or click the button below
              </div>
              <label style={{ display: "inline-block", background: TEAL, color: "#fff", borderRadius: 7, padding: "10px 22px", fontFamily: "sans-serif", fontSize: 13, fontWeight: "bold", cursor: "pointer" }}>
                📁 Choose PDF File
                <input type="file" accept="application/pdf" style={{ display: "none" }} onChange={e => setPdfFile(e.target.files[0])} />
              </label>
            </div>
            {pdfFile && (
              <div style={{ display: "flex", alignItems: "center", gap: 10, background: TEAL_LIGHT, border: `1px solid ${TEAL}`, borderRadius: 8, padding: "12px 16px", marginTop: 12 }}>
                <span>📄</span>
                <span style={{ flex: 1, fontSize: 13, color: NAVY, fontFamily: "sans-serif", fontWeight: "bold", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{pdfFile.name}</span>
                <button onClick={() => setPdfFile(null)} style={{ background: "none", border: "none", cursor: "pointer", color: "#8A9BAA", fontSize: 18 }}>✕</button>
              </div>
            )}
          </div>

          <div style={{ background: "#fff", borderRadius: 12, border: "1px solid #DDE4EB", padding: 28, boxShadow: "0 2px 12px rgba(13,43,69,0.06)" }}>
            <div style={{ color: NAVY, fontSize: 13, fontWeight: "bold", fontFamily: "sans-serif", textTransform: "uppercase", letterSpacing: 1, marginBottom: 16 }}>🩺 Clinical Notes</div>
            <textarea
              style={{ width: "100%", minHeight: 200, border: "1.5px solid #DDE4EB", borderRadius: 8, padding: "14px 16px", fontFamily: "Georgia, serif", fontSize: 14, color: NAVY, lineHeight: 1.7, resize: "vertical", outline: "none", boxSizing: "border-box", background: "#FAFBFC" }}
              placeholder={"Type your clinical shorthand here…\n\nExamples:\n• 52F HTN DM2, f/u, BP 136/82, A1c 7.1\n• Referral to cardiology, exertional chest pain"}
              value={freeText}
              onChange={e => setFreeText(e.target.value)}
            />
            <div style={{ fontSize: 12, color: "#8A9BAA", fontFamily: "sans-serif", marginTop: 8 }}>Abbreviations and shorthand are fine.</div>
          </div>
        </div>

        <button
          onClick={run}
          disabled={!canRun}
          style={{ width: "100%", background: canRun ? TEAL : "#B0C4CE", color: "#fff", border: "none", borderRadius: 10, padding: "18px 0", fontSize: 16, fontFamily: "sans-serif", fontWeight: "bold", cursor: canRun ? "pointer" : "not-allowed", marginBottom: 20, display: "flex", alignItems: "center", justifyContent: "center", gap: 10 }}
        >
          {loading
            ? <><span style={{ display: "inline-block", width: 18, height: 18, border: "2px solid rgba(255,255,255,0.4)", borderTopColor: "#fff", borderRadius: "50%", animation: "spin 0.7s linear infinite" }} /> Processing...</>
            : "✨ Complete Form with AI"}
        </button>

        {progress && (
          <div style={{ background: "#EEF5F5", borderRadius: 8, padding: "16px 20px", fontFamily: "sans-serif", fontSize: 14, color: TEAL, display: "flex", alignItems: "center", gap: 12, marginBottom: 20 }}>
            <span style={{ display: "inline-block", width: 16, height: 16, border: "2px solid rgba(11,110,110,0.3)", borderTopColor: TEAL, borderRadius: "50%", animation: "spin 0.7s linear infinite" }} />
            {progress}
          </div>
        )}

        {error && (
          <div style={{ background: "#FDF2F2", border: `1px solid ${RED}`, borderRadius: 8, padding: "16px 20px", color: RED, fontFamily: "sans-serif", fontSize: 14, marginBottom: 20 }}>
            ⚠️ {error}
          </div>
        )}

        {result && (
          <div style={{ background: "#fff", borderRadius: 12, border: `1.5px solid ${TEAL}`, padding: 28, boxShadow: "0 2px 12px rgba(11,110,110,0.08)" }}>
            <div style={{ color: TEAL, fontSize: 15, fontWeight: "bold", marginBottom: 16, fontFamily: "sans-serif", textTransform: "uppercase", letterSpacing: 1 }}>✅ Form Completed</div>
            <p style={{ fontFamily: "sans-serif", fontSize: 13, color: "#5A7A8A", marginBottom: 20 }}>
              <strong style={{ color: NAVY }}>{result.form_title}</strong> — {result.summary}
            </p>
            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 14, marginBottom: 20 }}>
              {result.fields.map((f, i) => (
                <div key={i} style={{ background: "#F7FBFB", border: "1px solid #D0E8E8", borderRadius: 8, padding: "12px 16px" }}>
                  <div style={{ fontSize: 11, color: "#7A9AA0", fontFamily: "sans-serif", textTransform: "uppercase", letterSpacing: 0.8, marginBottom: 4 }}>{f.label}</div>
                  <div style={{ fontSize: 14, color: NAVY, fontFamily: "Georgia, serif" }}>{f.value}</div>
                </div>
              ))}
            </div>
            {result.unfilled_fields?.length > 0 && (
              <div style={{ background: "#FEF9EC", border: "1px solid #E8C96A", borderRadius: 8, padding: "12px 16px", marginBottom: 20, fontFamily: "sans-serif", fontSize: 13, color: "#8A6A10" }}>
                <strong>Fields needing your input:</strong> {result.unfilled_fields.join(", ")}
              </div>
            )}
            <button
              onClick={() => generateDownload(result.form_title, result.fields, result.fileName)}
              style={{ background: NAVY, color: "#fff", border: "none", borderRadius: 8, padding: "14px 28px", fontSize: 14, fontFamily: "sans-serif", fontWeight: "bold", cursor: "pointer" }}
            >
              ⬇️ Download Completed Form
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
